#!/bin/bash
#include <stdio.h>

/**

 * main - prints the size of various types

 * Return: 0 if exited properly, non zero otherwise

 */

int main(void)

{

puts("\"Programming is like building a multilingual puzzle");

return (0);

}

© 2022 GitHub, Inc.
